### PR TITLE
Dependencies | November 14th 2023

### PR DESCRIPTION
**Pull request by coldlink**
## What does this change?

Changes from previous https://github.com/guardian/gateway/pull/2464

- Brings our dependencies up to the latest versions where possible

Holds back the following:

* Pin `@guardian/ab-react` to `4.0.1` due to issues which CSTI are looking into
* `eslint-plugin-functional` causing some eslint issues when upgrading to v6, so will hold back for now
* `@guardian/consent-management-platform` has some typescript declaration file issues in `13.7.2`
```sh
$ tsc --noEmit --skipLibCheck
src/client/lib/hooks/useCmpConsent.ts:2:30 - error TS2307: Cannot find module '@guardian/consent-management-platform/dist/types' or its corresponding type declarations.

2 import { ConsentState } from '@guardian/consent-management-platform/dist/types';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/client/lib/hooks/useCmpConsent.ts:3:27 - error TS7016: Could not find a declaration file for module '@guardian/consent-management-platform'. '/Users/mahesh_makani/code/guardian/gateway/node_modules/@guardian/consent-management-platform/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/guardian__consent-management-platform` if it exists or add a new declaration (.d.ts) file containing `declare module '@guardian/consent-management-platform';`

3 import { onConsent } from '@guardian/consent-management-platform';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/client/static/index.tsx:4:21 - error TS7016: Could not find a declaration file for module '@guardian/consent-management-platform'. '/Users/mahesh_makani/code/guardian/gateway/node_modules/@guardian/consent-management-platform/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/guardian__consent-management-platform` if it exists or add a new declaration (.d.ts) file containing `declare module '@guardian/consent-management-platform';`

4 import { cmp } from '@guardian/consent-management-platform';
```

## Tested

- [x] CODE

### CODE REVIEW

**Review by kelvin-chappell — APPROVED** [review]
👍
